Repository Team-TMB/backend, pull requests merged in 2024-07, with the labels that each got.

#262 OAuth2SuccessHandler 토큰 메서드 네임 수정
  src/main/java/com/example/baseballprediction/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: refactor

#265 cors config 수정
  src/main/java/com/example/baseballprediction/global/config/SecurityConfig.java
Labels: refactor

#268 cors config 수정
  src/main/java/com/example/baseballprediction/global/config/SecurityConfig.java
Labels: refactor

#267 style : 코드 컨벤션에 의한 코드 수정
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
Labels: style

#269 Refresh Token 쿠키 추가 시, 도메인 수정
  src/main/java/com/example/baseballprediction/domain/member/controller/LoginController.java
Labels: bug

#270 쿠키 발급 시, 도메인 오타 수정
  src/main/java/com/example/baseballprediction/domain/member/controller/LoginController.java
Labels: bug

#271 refresh token 롤백
  src/main/java/com/example/baseballprediction/domain/member/controller/LoginController.java
  src/main/java/com/example/baseballprediction/domain/member/dto/MemberResponse.java
  src/main/java/com/example/baseballprediction/domain/member/service/LoginService.java
  src/main/java/com/example/baseballprediction/global/security/oauth/dto/OAuthResponse.java
  src/main/java/com/example/baseballprediction/global/security/oauth/service/OAuth2MemberService.java
Labels: enhancement

#273 security config 롤백
  src/main/java/com/example/baseballprediction/global/config/SecurityConfig.java
Labels: enhancement

#275 프로필 온보딩 단계에서 사용자 최초가입여부 업데이트 하도록 수정
  src/main/java/com/example/baseballprediction/domain/member/entity/Member.java
  src/main/java/com/example/baseballprediction/domain/member/service/ProfileService.java
  src/test/java/com/example/baseballprediction/domain/game/service/GameServiceTest.java
  src/test/java/com/example/baseballprediction/domain/member/controller/LoginControllerTest.java
  src/test/java/com/example/baseballprediction/domain/member/service/LoginServiceTest.java
  src/test/java/com/example/baseballprediction/domain/member/service/ProfileServiceTest.java
Labels: refactor

#278 Refactor: 채팅방 투표율 결과 데이터 수정
  src/main/java/com/example/baseballprediction/domain/chat/controller/ChatController.java
Labels: refactor

#281 지난 승부예측 조회 시, 날짜순으로 정렬 안되는 문제 수정
  src/main/java/com/example/baseballprediction/domain/game/service/GameService.java
Labels: bug

#284 승부예측 히스토리, 선물내역 히스토리 조회 시, 페이지 번호 예외처리 추가
  src/main/java/com/example/baseballprediction/domain/member/controller/HistoryController.java
  src/main/java/com/example/baseballprediction/domain/monthlyfairy/controller/MonthlyFairyReplyController.java
  src/main/java/com/example/baseballprediction/global/constant/ErrorCode.java
Labels: refactor

#287 Refactor:페이지 네이션 RuntimeException수정
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
Labels: refactor
