Repository Team-TMB/backend, pull requests merged in 2024-04, with the labels that each got.

#193 오늘의 승부예측 댓글 조회 API, 비로그인 시 NPE 오류 수정
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
  src/main/java/com/example/baseballprediction/domain/reply/repository/ReplyRepositoryCustomImpl.java
  src/main/java/com/example/baseballprediction/domain/reply/service/ReplyService.java
Labels: bug

#196 Refactor: dto병합 작업 & 사용하지 않는 클래스 삭제
  src/main/java/com/example/baseballprediction/domain/chat/controller/ChatController.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatEventDTO.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatGiftRequestDTO.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatLeaveMessage.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatLeaveRequest.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatMessage.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatProfileDTO.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatRequestDTO.java
  src/main/java/com/example/baseballprediction/domain/chat/minigame/dto/MiniGameVoteDTO.java
  src/main/java/com/example/baseballprediction/domain/chat/minigame/entity/MiniGame.java
  src/main/java/com/example/baseballprediction/domain/chat/minigame/service/MiniGameService.java
  src/main/java/com/example/baseballprediction/domain/chat/service/ChatService.java
  src/main/java/com/example/baseballprediction/domain/gamevote/service/GameVoteService.java
  src/main/java/com/example/baseballprediction/domain/member/service/MemberService.java
  src/main/java/com/example/baseballprediction/global/constant/ErrorCode.java
  src/main/java/com/example/baseballprediction/global/error/exception/InsufficientTokenException.java
  src/main/java/com/example/baseballprediction/global/stomp/handler/StompHandler.java
Labels: refactor

#197 경기 종료 시, 채팅방 세션 삭제 로직 수정 (AOP 적용)
  src/main/java/com/example/baseballprediction/domain/chat/service/ChatService.java
  src/main/java/com/example/baseballprediction/domain/game/service/GameService.java
  src/main/java/com/example/baseballprediction/global/aspect/ChatAspect.java
Labels: refactor

#199 KBO 스코어 업데이트 스케줄러 스케줄 수정
  src/main/java/com/example/baseballprediction/global/schedule/service/GameScheduleService.java
  src/main/java/com/example/baseballprediction/global/scrape/service/ScrapeService.java
Labels: enhancement, refactor

#202 README.md 작성
  README.md
Labels: documentation

#207 경기 스코어 업데이트 평일 스케쥴러 시간 조정
  src/main/java/com/example/baseballprediction/global/schedule/service/GameScheduleService.java
Labels: bug

#209 Refactor: 미니게임 스케줄러에서 AOP변경 작업
  src/main/java/com/example/baseballprediction/domain/chat/minigame/service/MiniGameService.java
  src/main/java/com/example/baseballprediction/global/aspect/ChatAspect.java
Labels: refactor

#213 Refactor: 오늘의 승부예측 url변경 & 비회원 , 회원에 따른 로직 수정
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
  src/main/java/com/example/baseballprediction/domain/game/service/GameService.java
  src/main/java/com/example/baseballprediction/domain/gamevote/repository/GameVoteRepository.java
  src/main/java/com/example/baseballprediction/domain/gamevote/repository/GameVoteRepositoryCustom.java
  src/main/java/com/example/baseballprediction/domain/gamevote/repository/GameVoteRepositoryCustomImpl.java
Labels: refactor

#215 application 기본 profile 수정
  src/main/resources/application.yml
Labels: bug

#218 feat : ChatRequestDTO 생성자 정의
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatRequestDTO.java
Labels: enhancement

#222 fix : title 문자연결 오류 수정
  src/main/java/com/example/baseballprediction/domain/member/repository/MemberRepository.java
Labels: bug

#228 기능 단위 클래스 상세 분리로 인해 테스트 클래스도 동일하게 적용
  src/test/java/com/example/baseballprediction/domain/member/service/HistoryServiceTest.java
  src/test/java/com/example/baseballprediction/domain/member/service/ProfileServiceTest.java
  src/test/java/com/example/baseballprediction/domain/reply/service/ReplyServiceTest.java
Labels: refactor

#229 GameService 테스트 코드 작성
  src/test/java/com/example/baseballprediction/domain/game/service/GameServiceTest.java
  src/test/java/com/example/baseballprediction/domain/member/service/ProfileServiceTest.java
Labels: refactor

#232 TeamService 테스트 코드 작성
  src/test/java/com/example/baseballprediction/domain/team/service/TeamServiceTest.java
Labels: enhancement
