Repository Team-TMB/backend, pull requests merged in 2024-03, with the labels that each got.

#132 Refactor: SecurityConfig에서 permitAll 설정
  src/main/java/com/example/baseballprediction/global/config/SecurityConfig.java
Labels: refactor

#135 댓글 조회 오류 수정
  src/main/java/com/example/baseballprediction/domain/reply/repository/ReplyRepositoryCustomImpl.java
Labels: bug

#137 댓글 조회 시, 좋아요 TOP 3 댓글 우선 조회
  src/main/java/com/example/baseballprediction/domain/reply/service/ReplyService.java
Labels: enhancement, refactor

#139 댓글 조회 응답 DTO 필드 수정
  src/main/java/com/example/baseballprediction/domain/reply/dto/ReplyResponse.java
Labels: refactor

#143 댓글 좋아요 취소 컨트롤러 매핑 추가
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
  src/main/java/com/example/baseballprediction/domain/monthlyfairy/controller/MonthlyFairyController.java
Labels: enhancement

#146 Refactor : 선물하기 기능 수정
  src/main/java/com/example/baseballprediction/domain/chat/controller/ChatController.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatGiftRequestDTO.java
  src/main/java/com/example/baseballprediction/domain/gifttoken/entity/GiftToken.java
  src/main/java/com/example/baseballprediction/domain/member/service/MemberService.java
Labels: refactor

#147 댓글 조회 시, 좋아요 여부 필드 추가
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
  src/main/java/com/example/baseballprediction/domain/monthlyfairy/controller/MonthlyFairyController.java
  src/main/java/com/example/baseballprediction/domain/reply/dto/ReplyLikeProjection.java
  src/main/java/com/example/baseballprediction/domain/reply/dto/ReplyResponse.java
  src/main/java/com/example/baseballprediction/domain/reply/repository/ReplyRepositoryCustomImpl.java
  src/main/java/com/example/baseballprediction/domain/reply/service/ReplyService.java
Labels: refactor

#148 대댓글 조회 시, 좋아요 여부 필드 추가
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
  src/main/java/com/example/baseballprediction/domain/monthlyfairy/controller/MonthlyFairyController.java
  src/main/java/com/example/baseballprediction/domain/reply/repository/ReplyRepository.java
  src/main/java/com/example/baseballprediction/domain/reply/service/ReplyService.java
Labels: refactor

#150 경기 스코어 업데이트 크롤링 오류 수정
  src/main/java/com/example/baseballprediction/domain/game/entity/Game.java
  src/main/java/com/example/baseballprediction/global/scrape/service/ScrapeService.java
Labels: bug

#152 Refactor : 미니투표 종료 status처리 & 채팅방 나가기
  src/main/java/com/example/baseballprediction/domain/chat/controller/ChatController.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatLeaveMessage.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatLeaveRequest.java
  src/main/java/com/example/baseballprediction/domain/chat/minigame/entity/MiniGame.java
  src/main/java/com/example/baseballprediction/domain/chat/minigame/repository/MiniGameRepository.java
  src/main/java/com/example/baseballprediction/domain/chat/minigame/service/MiniGameService.java
  src/main/java/com/example/baseballprediction/domain/chat/service/ChatService.java
  src/main/java/com/example/baseballprediction/global/constant/ErrorCode.java
Labels: refactor

#166 선물내역 조회 시, 프로필 이미지가 아닌 응원하는 팀 팀명 응답하도록 수정
  src/main/java/com/example/baseballprediction/domain/member/dto/MemberResponse.java
Labels: refactor

#170 Refactor: 오늘의 승부예측 List response값 수정
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
  src/main/java/com/example/baseballprediction/domain/game/dto/GameResponse.java
  src/main/java/com/example/baseballprediction/domain/game/service/GameService.java
  src/main/java/com/example/baseballprediction/domain/gamevote/repository/GameVoteRepository.java
Labels: refactor

#172 fix: x-frame-option 오류 수정
  src/main/java/com/example/baseballprediction/global/config/WebSockConfig.java
Labels: bug

#174 SockJS 사용 시, 웹소켓 연결 오류 수정
  src/main/java/com/example/baseballprediction/global/config/SecurityConfig.java
Labels: bug

#178 Status.PROGRESS name 수정
  src/main/java/com/example/baseballprediction/global/constant/Status.java
Labels: bug

#180 KBO 홈페이지 경기취소 업데이트 안되는 오류 수정
  src/main/java/com/example/baseballprediction/global/scrape/service/ScrapeService.java
Labels: bug

#182 선물하기, 선물내역 조회 시 한마디 기능 추가
  src/main/java/com/example/baseballprediction/domain/chat/controller/ChatController.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatGiftRequestDTO.java
  src/main/java/com/example/baseballprediction/domain/member/dto/MemberResponse.java
  src/main/java/com/example/baseballprediction/domain/member/service/MemberService.java
  src/main/resources/h2/schema.sql
Labels: enhancement

#184 소셜 로그인 시, 별도 응답 API 추가
  src/main/java/com/example/baseballprediction/domain/gifttoken/entity/GiftToken.java
  src/main/java/com/example/baseballprediction/domain/member/controller/MemberController.java
  src/main/java/com/example/baseballprediction/domain/member/entity/Member.java
  src/main/java/com/example/baseballprediction/domain/member/service/MemberService.java
  src/main/java/com/example/baseballprediction/global/security/MemberDetails.java
  src/main/java/com/example/baseballprediction/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/resources/h2/data.sql
  src/main/resources/h2/schema.sql
Labels: enhancement

#188 프로필 조회 API 조건 id -> nickname으로 수정
  src/main/java/com/example/baseballprediction/domain/member/controller/MemberController.java
  src/main/java/com/example/baseballprediction/domain/member/repository/MemberRepository.java
  src/main/java/com/example/baseballprediction/domain/member/service/MemberService.java
Labels: refactor

#189 OAuth2 로그인 시, 토큰 발급 로직 수정
  build.gradle
  src/main/java/com/example/baseballprediction/domain/member/controller/MemberController.java
  src/main/java/com/example/baseballprediction/global/config/SecurityConfig.java
  src/main/java/com/example/baseballprediction/global/security/MemberDetails.java
  src/main/java/com/example/baseballprediction/global/security/oauth/dto/OAuthResponse.java
  src/main/java/com/example/baseballprediction/global/security/oauth/memberinfo/KakaoMemberInfo.java
  src/main/java/com/example/baseballprediction/global/security/oauth/service/Fetch.java
  src/main/java/com/example/baseballprediction/global/security/oauth/service/KakaoApiClient.java
  src/main/java/com/example/baseballprediction/global/security/oauth/service/OAuth2ApiClient.java
  src/main/java/com/example/baseballprediction/global/security/oauth/service/OAuth2MemberService.java
  src/main/java/com/example/baseballprediction/global/security/oauth/token/KakaoToken.java
  src/main/resources-env/prod/application.yml
Labels: refactor

#191 application.yml naver.state 값 추가
  src/main/resources-env/prod/application.yml
Labels: enhancement
