Repository Team-TMB/backend, pull requests merged in 2024-01, with the labels that each got.

#61 API 서버 HealthCheck 오류 수정
  src/main/java/com/example/baseballprediction/global/config/SecurityConfig.java
Labels: bug

#70 Feat: 오늘의 승부예측 댓글 작성 api
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
Labels: feature

#71 오늘의 승부예측 댓글 좋아요 api
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
Labels: feature

#72 오늘의 승부예측 댓글 조회 api
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
  src/main/java/com/example/baseballprediction/domain/game/dto/GameReplyDTO.java
  src/main/java/com/example/baseballprediction/domain/game/dto/GameReplyLikeProjection.java
  src/main/java/com/example/baseballprediction/domain/reply/entity/Reply.java
  src/main/java/com/example/baseballprediction/domain/reply/repository/ReplyRepository.java
  src/main/java/com/example/baseballprediction/domain/reply/service/ReplyService.java
  src/main/java/com/example/baseballprediction/domain/replylike/entity/ReplyLike.java
  src/main/java/com/example/baseballprediction/domain/replylike/repository/ReplyLikeRepository.java
Labels: feature

#81 닉네임 중복확인 API 구현
  src/main/java/com/example/baseballprediction/domain/member/controller/MemberController.java
  src/main/java/com/example/baseballprediction/domain/member/dto/MemberRequest.java
  src/main/java/com/example/baseballprediction/domain/member/dto/MemberResponse.java
  src/main/java/com/example/baseballprediction/domain/member/service/MemberService.java
Labels: enhancement

#90 Refator: 오늘의 승부예측 투표 팀명 추가
  src/main/java/com/example/baseballprediction/domain/game/dto/GameResponse.java
Labels: refactor

#93 월간 승리요정 집계 기능 구현
  src/main/java/com/example/baseballprediction/BaseballPredictionApplication.java
  src/main/java/com/example/baseballprediction/domain/game/repository/GameRepository.java
  src/main/java/com/example/baseballprediction/domain/member/entity/Member.java
  src/main/java/com/example/baseballprediction/domain/monthlyfairy/entity/MonthlyFairy.java
  src/main/java/com/example/baseballprediction/domain/team/entity/Team.java
  src/main/java/com/example/baseballprediction/global/schedule/service/MonthlyFairyScheduleService.java
  src/main/java/com/example/baseballprediction/global/util/CustomDateUtil.java
Labels: enhancement

#95 서버 타임존 설정 스크립트 오류 수정
  .ebextensions/setup-timezone.config
Labels: bug

#96 타임존 스크립트 파일명 수정
  .ebextensions/01-setup-timezone.config
Labels: refactor

#97 workflow 배포 스크립트 수정
  .github/workflows/deploy.yml
Labels: refactor
