Repository Team-TMB/backend, pull requests merged in 2024-02, with the labels that each got.

#115 로그인 API 응답 바디에 팀명 항목 추가
  src/main/java/com/example/baseballprediction/domain/member/dto/MemberResponse.java
  src/main/java/com/example/baseballprediction/global/security/oauth/dto/OAuthResponse.java
  src/main/java/com/example/baseballprediction/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: enhancement

#116 로그아웃 기능 구현
  src/main/java/com/example/baseballprediction/domain/member/controller/MemberController.java
  src/main/java/com/example/baseballprediction/global/config/SecurityConfig.java
  src/main/java/com/example/baseballprediction/global/security/jwt/handler/JwtLogoutHandler.java
Labels: enhancement

#119 닉네임 중복확인 API 요청 바디 -> 파라미터로 수정
  src/main/java/com/example/baseballprediction/domain/member/controller/MemberController.java
  src/main/java/com/example/baseballprediction/domain/member/dto/MemberRequest.java
  src/main/java/com/example/baseballprediction/global/constant/ErrorCode.java
Labels: bug, refactor

#117 Feat : 채팅방 api
  build.gradle
  src/main/java/com/example/baseballprediction/domain/chat/controller/ChatController.java
  src/main/java/com/example/baseballprediction/domain/chat/controller/ChatRoomController.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatMessage.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatProfileDTO.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatRoom.java
  src/main/java/com/example/baseballprediction/domain/chat/service/ChatService.java
  src/main/java/com/example/baseballprediction/domain/member/repository/MemberRepository.java
  src/main/java/com/example/baseballprediction/global/config/WebSockConfig.java
  src/main/java/com/example/baseballprediction/global/constant/ChatType.java
  src/main/java/com/example/baseballprediction/global/error/handler/StompHandler.java
Labels: feature

#128 운영 chromedriver 경로 수정
  src/main/resources-env/prod/application.yml
Labels: bug

#129 Feat: 토큰 선물하기 & 채팅방 api 리팩토링
  build.gradle
  src/main/java/com/example/baseballprediction/domain/chat/controller/ChatController.java
  src/main/java/com/example/baseballprediction/domain/chat/controller/ChatRoomController.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatGiftRequestDTO.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatMessage.java
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatRoom.java
  src/main/java/com/example/baseballprediction/domain/chat/service/ChatService.java
  src/main/java/com/example/baseballprediction/domain/member/entity/Member.java
  src/main/java/com/example/baseballprediction/domain/member/repository/MemberRepository.java
  src/main/java/com/example/baseballprediction/domain/member/service/MemberService.java
  src/main/java/com/example/baseballprediction/global/config/WebSockConfig.java
  src/main/java/com/example/baseballprediction/global/constant/ErrorCode.java
  src/main/java/com/example/baseballprediction/global/error/exception/InsufficientTokenException.java
  src/main/java/com/example/baseballprediction/global/error/handler/StompHandler.java
  src/main/java/com/example/baseballprediction/global/security/MemberDetails.java
  src/main/java/com/example/baseballprediction/global/stomp/handler/StompHandler.java
Labels: feature, refactor
