Repository Team-TMB/backend, pull requests merged in 2024-06, with the labels that each got.

#241 REST Docs 의존성 추가 및 환경설정
  build.gradle
Labels: enhancement

#243 필드명 컨벤션 안맞는 필드 수정
  src/main/java/com/example/baseballprediction/domain/chat/dto/ChatEventDTO.java
  src/main/java/com/example/baseballprediction/domain/chat/minigame/dto/MiniGameVoteDTO.java
Labels: refactor

#245 ChatService 테스트 코드 작성
  src/main/java/com/example/baseballprediction/domain/chat/service/ChatService.java
  src/test/java/com/example/baseballprediction/domain/chat/service/ChatServiceTest.java
Labels: refactor

#246 LoginService 테스트 코드 작성
  src/main/java/com/example/baseballprediction/domain/member/service/LoginService.java
  src/test/java/com/example/baseballprediction/domain/member/service/LoginServiceTest.java
Labels: enhancement

#251 프로필 팝업 조회 응답 필드 추가
  src/main/java/com/example/baseballprediction/domain/member/dto/ProfileProjection.java
  src/main/java/com/example/baseballprediction/domain/member/repository/MemberRepository.java
Labels: enhancement

#253 refactor: 오늘의 승부예측 page 인덱스 수정
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
Labels: refactor

#255 Feat : gameId로 게임 내역 단건 조회 api
  src/main/java/com/example/baseballprediction/domain/game/controller/GameController.java
  src/main/java/com/example/baseballprediction/domain/game/service/GameService.java
Labels: feature

#257 좋아요 있는 댓글 삭제 시, 삭제 안되는 오류 수정
  src/main/java/com/example/baseballprediction/domain/reply/entity/Reply.java
  src/test/java/com/example/baseballprediction/domain/reply/service/ReplyServiceTest.java
Labels: bug
